version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/ubuntu/apache/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "8080:80"
    volumes:
      - ./:/root/bash_cms_server
      - ../bash_cms_front:/var/www/bash_cms_front
